swift_build_tool: "xcodebuild"

build_tool_arguments:
  - "-scheme"
  - "ImproveAI"
  - "-destination"
  - "platform=iOS Simulator,OS=16.0,name=iPhone 13"
  - "-sdk"
  - "iphonesimulator"

exclude:
  - ImproveAISwift/internal/*
  - ImproveAISwift/IMPError.swift
title: Improve AI iOS SDK
author: Improve AI
author_url: https://improve.ai
github_url: https://github.com/improve-ai/ios-sdk
root_url: https://improve-ai.github.io/ios-sdk/
theme: fullwidth
